spring:
  datasource:
    url: jdbc:postgresql://safe-mobis.cl92zanhxwsm.ap-northeast-2.rds.amazonaws.com:5432/safe_mobis
    username: postgres
    password: ENC(u+blv0TlhsG9nJyS0bFnv7rE8pxjsr+U)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    database: postgresql
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    open-in-view: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.SQL: debug
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

awsParameterStorePropertySource:
  enabled: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${/vroomvroom/cloud-parameter-store/jasypt.encryptor.password}
