spring:
  datasource:
    url: jdbc:mysql://safe-mobis.cl92zanhxwsm.ap-northeast-2.rds.amazonaws.com:3306/safe_mobis?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: admin
    password: ENC(u+blv0TlhsG9nJyS0bFnv7rE8pxjsr+U)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 177000

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    open-in-view: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.SQL: debug
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

awsParameterStorePropertySource:
  enabled: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${/vroomvroom/cloud-parameter-store/jasypt.encryptor.password}
